mysite/contact/urls.py
from django.conf.urls import url
from .views.contact import ContactView

app_name = 'contact'

urlpatterns = [
    url(r'^$', ContactView.as_view(), name='contact'),
]

mysite/customer/urls.py
from django.conf.urls import url
from .views.customer import CustomerListView
from .views.add_customer import AddCustomer
from .views.update_customer import UpdateCustomer
from .views.delete_customer import DeleteCustomer
from .views.upload_profile import UploadCustomerProfile

app_name = 'customer'

urlpatterns = [
    url(r'^$', CustomerListView.as_view(), name='customer'),
    url(r'^add$', AddCustomer.as_view(), name='add_customer'),
    url(r'^update/(?P<customer_id>[0-9]+)$', UpdateCustomer.as_view(), name='update_customer'),
    url(r'^delete/(?P<customer_id>[0-9]+)$', DeleteCustomer.as_view(), name="delete_customer"),
    url(r'^upload_profile/(?P<customer_id>[0-9]+)$', UploadCustomerProfile.as_view(), name="upload_profile_customer"),
]

mysite/dashboard/urls.py
from django.conf.urls import url
from .views.dashboard import DashBoardView

app_name = 'dashboard'

urlpatterns = [
    url(r'^$', DashBoardView.as_view(), name='dashboard'),
]

mysite/moto/urls.py
from django.conf.urls import url

app_name = "moto"

urlpatterns = [

]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^customer/', include('customer.urls')),
    url(r'^moto/', include('moto.urls')),
]

mysite/contact/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/customer/models.py
from __future__ import unicode_literals
import datetime

from django.db import models

# Create your models here.
# CREATE TABLE myapp_person (
#     "id" serial NOT NULL PRIMARY KEY,
#     "first_name" varchar(30) NOT NULL,
#     "last_name" varchar(30) NOT NULL,
#     "image_url" varchar(20000) NOT NULL
# );


class Customer(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    image_url = models.CharField(max_length=20000)
    date_of_birth = models.DateTimeField('date of birth', default=datetime.date.today)
    age = models.IntegerField(default=0)

    def __str__(self):
        return self.first_name + self.last_name

mysite/dashboard/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

mysite/moto/models.py
from django.db import models

# Create your models here.
# many-to-one relationship


class Manufacturer(models.Model):
    name = models.CharField(max_length=50)
    age = models.IntegerField(default=0)


class Car(models.Model):
    # foreignKey field name should be the name of the Model in lowercase
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

# many to many relationship


class Topping(models.Model):
    pass


class Pizza(models.Model):
    # the name of ManyToManyField should be the plural version of the Model
    # it does not matter which model will have ManyToManyField, but it should be existed in only one model, not both
    toppings = models.ManyToManyField(Topping)

# extra fields in many to many relationship


class Person(models.Model):
    name = models.CharField(max_length=128)


class Group(models.Model):
    name = models.CharField(max_length=128)
    members = models.ManyToManyField(Person, through='Membership')


class Membership(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    date_joined = models.DateField()
    invite_reason = models.CharField(max_length=64)


# meta data
class Ox(models.Model):
    horn_length = models.IntegerField()

    class Meta:
        ordering = ["horn_length"]
        verbose_name_plural = "oxen"
        # ordering, database - table name

mysite/contact/views/contact.py
from django.views.generic.base import TemplateView


class ContactView(TemplateView):
    template_name = 'contact/contact.tpl.html'

mysite/customer/views/add_customer.py
from customer.models import Customer
from django.views.generic.base import TemplateView
from django.core.files.storage import FileSystemStorage
from django.shortcuts import render, redirect


class AddCustomer(TemplateView):
    template_name = 'customer/add_customer.tpl.html'

    def post(self, request, *args, **kwargs):
         context = super(AddCustomer, self).get_context_data(**kwargs)
         if request.FILES['customer_image']:
             customer_image = request.FILES['customer_image']
             fs = FileSystemStorage()
             filename = fs.save(customer_image.name, customer_image)
             uploaded_file_url = fs.url(filename)
         first_name = request.POST['first_name']
         last_name = request.POST['last_name']
         image_url = uploaded_file_url
         age = request.POST['age']
         customer = Customer.objects.create(first_name = first_name, last_name = last_name, image_url = image_url, age = age)
         try:
            customer.save()
         except:
              return render(request, self.template_name, context=context)
         else:
              return redirect('customer:customer')

mysite/customer/views/customer.py
from django.views.generic.base import TemplateView
from customer.models import Customer


class CustomerListView(TemplateView):
    template_name = 'customer/customer.tpl.html'

    def get_context_data(self, **kwargs):
        context = super(CustomerListView, self).get_context_data(**kwargs)
        customer_list = Customer.objects.all()
        context.update({
            "customer_list": customer_list
        })
        return context

mysite/customer/views/delete_customer.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
from customer.models import Customer


class DeleteCustomer(TemplateView):

    def get(self, request, *args, **kwargs):
        context = super(DeleteCustomer, self).get_context_data(**kwargs)
        customer_id = context['customer_id']
        customer = Customer.objects.filter(id=customer_id)
        customer.delete()
        return redirect('customer:customer')

mysite/customer/views/update_customer.py
from customer.models import Customer
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect


class UpdateCustomer(TemplateView):
    template_name = 'customer/update_customer.tpl.html'

    def get_context_data(self, **kwargs):
        context = super(UpdateCustomer, self).get_context_data(**kwargs)
        customer_id = context['customer_id']
        customer = Customer.objects.get(id = customer_id)
        context.update({
            'customer': customer
        })
        return context

    def post(self, request, *args, **kwargs):
         context = super(UpdateCustomer, self).get_context_data(**kwargs)
         first_name = request.POST['first_name']
         last_name = request.POST['last_name']
         image_url = request.POST['image_url']
         age = request.POST['age']
         id = context['customer_id']
         customer = Customer(id = id, first_name = first_name, last_name = last_name, image_url = image_url, age = age)
         try:
            customer.save()
         except:
             customer_id = context['customer_id']
             customer = Customer.objects.filter(customer_id=customer_id)
             context.update({
                 'customer': customer
             })
             return render(request, self.template_name, context=context)
         else:
              return redirect('customer:customer')

mysite/customer/views/upload_profile.py
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage
from django.views.generic.base import TemplateView


class UploadCustomerProfile(TemplateView):
    template_name = 'customer/upload_profile.tpl.html'

    def post(self, request, *args, **kwargs):
        if request.FILES['myfile']:
            my_file = request.FILES['myfile']
            fs = FileSystemStorage()
            filename = fs.save(my_file.name, my_file)
            uploaded_file_url = fs.url(filename)
            return render(request, 'customer/upload_profile.tpl.html', {
                'uploaded_file_url': uploaded_file_url
            })

mysite/dashboard/views/dashboard.py
from django.views.generic.base import TemplateView
from django.http import JsonResponse


class DashBoardView(TemplateView):
    template_name = 'dashboard/dashboard.tpl.html'

    def post(self, request, *args, **kwargs):
        campaign_name = 1
        return JsonResponse({"status": 2, "msg": 'ok'})

mysite/contact/templates/contact/contact.tpl.html
{% extends 'base.tpl.html' %}
{% block main_content %}
    <div class="page-title">Contact</div>
{% endblock %}

mysite/customer/templates/customer/add_customer.tpl.html
{% extends 'base.tpl.html' %}
{% load static %}
{% block style_block %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'customer/customer.css' %}?{% now "U" %}">
{% endblock %}
{% block main_content %}
    <div class="page-title">Add Customer</div>
    <br><br>
    <form method="POST" enctype="multipart/form-data" action="{% url 'customer:add_customer' %}"  onsubmit="return submitFuc()">
        {% csrf_token %}
        <div class="form-group">
            <div class="row required">
                <label class="col-md-2" for="firstname">First Name:</label>
                <div class="col-md-3">
                    <input type="text" class="form-control" id="firstname" name="first_name" required>
                </div>
            </div>
        </div>
        <div class="form-group required">
            <div class="row">
                <label class="col-md-2" for="lastname">Last Name:</label>
                <div class="col-md-3">
                    <input type="text" class="form-control" id="lastname" name="last_name" required>
                </div>
            </div>
        </div>
        <div class="form-group required">
            <div class="row">
                <label class="col-md-2" for="customer_image">Image:</label>
                <div class="col-md-3">
                    <input type="file" name="customer_image" required>
                </div>
            </div>
        </div>
        <div class="form-group required">
            <div class="row">
                <label class="col-md-2" for="age">Age:</label>
                <div class="col-md-3">
                    <input type="number" min="0" class="form-control" id="age" name="age" required>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-md-5">
                    <input type="submit" class="btn btn-primary add-customer-submit-btn" value="Submit"/>
                </div>
            </div>
        </div>
    </form>
{% endblock %}
{% block js_block %}
    {{ block.super }}
    <script>
        var submitFuc = function() {
            console.log(123);
            //return false; to cancel submit action
        };
    </script>
{% endblock %}

mysite/customer/templates/customer/customer.tpl.html
{% extends 'base.tpl.html' %}
{% load static %}
{% block style_block %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'customer/customer.css' %}?{% now "U" %}">
{% endblock %}
{% block main_content %}
    <div class="page-title">Customer</div>
    <br><br>
    <div class="add-customer-btn">
        <a href="{% url 'customer:add_customer' %}">
            <input type="button" class="btn btn-primary" value="Add"  />
        </a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Image Url</th>
            <th>Age</th>
            <th>Action</th>
        </tr>
        </thead>
        <tbody>
        {% for customer in customer_list %}
            <tr>
                <td>{{ customer.first_name|default_if_none:'' }}</td>
                <td>{{ customer.last_name|default_if_none:'' }}</td>
                <td>{{ customer.image_url|default_if_none:'' }}</td>
                <td>{{ customer.age|default_if_none:'' }}</td>
                <td>
                    <a href="{% url 'customer:update_customer' customer.id %}">
                        <button class="btn btn-default btn-outline-green">Edit</button>
                    </a>
                    <a href="{% url 'customer:upload_profile_customer' customer.id %}">
                        <button class="btn btn-default btn-outline-green">Upload Profile</button>
                    </a>
                    <a href="{% url 'customer:delete_customer' customer.id %}">
                        <button class="btn btn-default btn-outline-red">Delete</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}
{% block js_block %}
    {{ block.super }}
{% endblock %}

mysite/customer/templates/customer/update_customer.tpl.html
{% extends 'base.tpl.html' %}
{% load static %}
{% block style_block %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'customer/customer.css' %}?{% now "U" %}">
{% endblock %}
{% block main_content %}
    <div class="page-title">Edit Customer</div>
    <br><br>
    <form method="POST" action="{% url 'customer:update_customer' customer.id %}" onsubmit="return submitFuc()">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-2">
                <img width="170" height="170" src="{{ customer.image_url|default_if_none:'' }}"/>
            </div>
            <div class="col-md-10">
                <div class="form-group">
                    <div class="row required">
                        <label class="col-md-2" for="firstname">First Name:</label>
                        <div class="col-md-3">
                            <input type="text" class="form-control" value="{{ customer.first_name|default_if_none:'' }}"
                                   id="firstname" name="first_name" required>
                        </div>
                    </div>
                </div>
                <div class="form-group required">
                    <div class="row">
                        <label class="col-md-2" for="lastname">Last Name:</label>
                        <div class="col-md-3">
                            <input type="text" class="form-control" value="{{ customer.last_name|default_if_none:'' }}"
                                   id="lastname" name="last_name" required>
                        </div>
                    </div>
                </div>
                <div class="form-group required" hidden>
                    <div class="row">
                        <label class="col-md-2" for="customer_image">Image:</label>
                        <div class="col-md-3">
                            <input type="text" class="form-control" value="{{ customer.image_url|default_if_none:'' }}"
                                   id="customer_image" name="image_url" required>
                        </div>
                    </div>
                </div>
                <div class="form-group required">
                    <div class="row">
                        <label class="col-md-2" for="age">Age:</label>
                        <div class="col-md-3">
                            <input type="number" min="0" class="form-control"
                                   value="{{ customer.age|default_if_none:'' }}" id="age" name="age" required>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-md-5">
                            <input type="submit" class="btn btn-primary add-customer-submit-btn" value="Submit"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}
{% block js_block %}
    {{ block.super }}
    <script>
        var submitFuc = function () {
            console.log(123);
            //return false; to cancel submit action
        };
    </script>
{% endblock %}

mysite/customer/templates/customer/upload_profile.tpl.html
{% extends 'base.tpl.html' %}


{% block main_content %}
    <div class="page-title">Upload Customer Profile</div>
    <br><br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="myfile">
        <br>
        <button type="submit" class="btn btn-primary">Upload</button>
        <a href="{% url 'customer:customer' %}">
            <button type="button" class="btn btn-default btn-cancel">Back</button>
        </a>
    </form>

    {% if uploaded_file_url %}
        <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
    {% endif %}

{% endblock %}

mysite/dashboard/templates/dashboard/dashboard.tpl.html
{% extends "base.tpl.html" %}
{% load static %}
{% block style_block %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'dashboard/dashboard.css' %}?{% now "U" %}">
{% endblock %}
{% block main_content %}
    <div class="page-title">Dashboard</div>
    <br/><br/>
    <div class="statistic-card-area row">
        <div class="statistic-card col-md-2 address-book col-sm-12">
            <div class="statistic-amount">200</div>
            <i class="fa fa-address-book" aria-hidden="true"></i>
        </div>
        <div class="statistic-card col-md-2 user-circle col-sm-12">
            <div class="statistic-amount">150</div>
            <i class="fa fa-user-circle" aria-hidden="true"></i>
        </div>
        <div class="statistic-card col-md-2 wpexplorer col-sm-12">
            <div class="statistic-amount">180</div>
            <i class="fa fa-wpexplorer" aria-hidden="true"></i>
        </div>
        <div class="statistic-card col-md-2 car col-sm-12">
            <div class="statistic-amount">220</div>
            <i class="fa fa-car" aria-hidden="true"></i>
        </div>
        <div class="statistic-card col-md-2 bug col-sm-12">
            <div class="statistic-amount">120</div>
            <i class="fa fa-bug" aria-hidden="true"></i>
        </div>
    </div>
{% endblock %}

mysite/templates/base.tpl.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Shop Shop</title>
    <meta name="description" content="">
    <link rel="shortcut icon" href="{% static 'images/favicon.jpg' %}">
    <meta name="viewport" content="width=device-width">
    {% block style_block %}
        <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'custom/style.css' %}?{% now "U" %}">
        <link rel="stylesheet" href="{% static 'custom/navbar.css' %}?{% now "U" %}">
    {% endblock %}
</head>
<body>
    <div class="app-content">
        <div class="left-side-bar">
            {% include 'navigation.tpl.html' %}
        </div>
        <div class="main-content">
            {% block main_content %}

            {% endblock %}
        </div>
    </div>
</body>
{% block js_block %}
    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
{% endblock %}
</html>

mysite/templates/header.tpl.html
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Shop Shop</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="dropdown">
      <li><a href="#" class="active">Dashboard</a></li>
      <li><a href="#">About</a></li>
    </ul>
  </div>
</nav>

mysite/templates/navigation.tpl.html
<div class="nav-side-menu">
    <div class="brand">Go Shop</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <a href="{% url 'dashboard:dashboard' %}">
                    <i class="fa fa-dashboard fa-lg"></i> Dashboard
                </a>
            </li>
            <li data-toggle="collapse" data-target="#service" class="collapsed">
                <a href="#"><i class="fa fa-gift fa-lg"></i> Products <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="service">
                <li>Clothes</li>
                <li>Books</li>
                <li>Tickets</li>
            </ul>
            <li>
                <a href="{% url 'customer:customer' %}">
                    <i class="fa fa-users fa-lg"></i> Customer
                </a>
            </li>
            <li>
                <a href="{% url 'contact:contact' %}">
                    <i class="fa fa-user fa-lg"></i> Contact Us
                </a>
            </li>
        </ul>
    </div>
</div>